[[main]]
  identifier = "learn"
  name = "learn"
  url = "learn"
  weight = 1

#[[main]]
#  identifier = "updates"
#  name = "Updates"
#  url = "updates"
#  weight = 2

[[main]]
  identifier = "tips"
  name = "Tips"
  url = "tips"
  weight = 2